export const SEARCH_TRACKS_LOADING = 'SEARCH_TRACKS_LOADING';
export const SEARCH_TRACKS_SUCCESS = 'SEARCH_TRACKS_SUCCESS';
export const SEARCH_TRACKS_ERROR = 'SEARCH_TRACKS_ERROR';

export const FETCH_FIRST_TRACKS = 'FETCH_FIRST_TRACKS';

export const START = 'START';
export const PLAY = 'PLAY';
